- hosts: role=worker
  gather_facts: no
  roles:
   - dfs-common

- hosts: role=worker[0]
  gather_facts: no
  roles:
   - dfs-master
- hosts: role=worker[1:]
  gather_facts: no
  roles:
   - dfs-datanode
